const students = [
    {
      number: 1,
      name: "Himanshu",
      ticket:1,
      rating:2,
      exam:5,
      more:'More Details',
      fullname:'Himanshu Gandhi',
      contact:'+91 8059026694',
      email:'Himanshukamboj135@gmail.com',
      address:'Haryana',
      field:'Cyber Security'

      },

    {
        number: 2,
        name: "Jaspinder",
        ticket:3,
        rating:2,
        exam:1,
        more:'More Details',
        fullname:'Jaspinder Gill',
        contact:'+91 111111111',
        email:'jaspinder@gmail.com',
        address:'Punjab',
        field:'Java'
    },
    {
        number: 3,
        name: "Shudhansu",
        ticket:4,
        rating:4,
        exam:4,
        more:'More Details',
        fullname:'Shudhansu',
        contact:'+91 2222222222',
        email:'Shudhansu@gmail.com',
        address:'Jammu',
        field:'Cyber Security'
    },
    {
        number: 4,
        name: "Dinesh",
        ticket:1,
        rating:2,
        exam:1,
        more:'More Details',
        fullname:'Dinesh',
        contact:'+91 333333333',
        email:'Dinesh@gmail.com',
        address:'Haryana',
        field:'Agriculure'
    },
    {
        number: 5,
        name: "Hemant",
        ticket:5,
        rating:1,
        exam:3,
        more:'More Details',
        fullname:'Hemant',
        contact:'+91 666666666',
        email:'Hemant@gmail.com',
        address:'UP',
        field:'MBA'
    },
    {
        number: 6,
        name: "Udit",
        ticket:6,
        rating:3,
        exam:3,
        more:'More Details',
        fullname:'Udit Matta',
        contact:'+91 77777777',
        email:'UditMatta@gmail.com',
        address:'Haryana',
        field:'MBA'
    },
    {
        number: 7,
        name: "Sushimta",
        ticket:7,
        rating:3,
        exam:1,
        more:'More Details',
        fullname:'Sushimta Soni',
        contact:'+91 99999999',
        email:'Sushimta@gmail.com',
        address:'Itely',
        field:'MBA'
    },
    {
        number: 8,
        name: "Anu",
        ticket:8,
        rating:2,
        exam:2,
        more:'More Details',
        fullname:'Anu ',
        contact:'+91 99945629',
        email:'Anu@gmail.com',
        address:'Hisar',
        field:'Cyber Security'
    },
    {
        number: 9,
        name: "Pooja",
        ticket:9,
        rating:0,
        exam:2,
        more:'More Details',
        fullname:'Pooja Singh',
        contact:'+91 165464688646',
        email:'Pooja@gmail.com',
        address:'UP',
        field:'Computer Science'
    },
    {
        number: 10,
        name: "Anil",
        ticket:9,
        rating:3,
        exam:7,
        more:'More Details',
        fullname:'Anil Kumar',
        contact:'+91 45468484684',
        email:'anil@gmail.com',
        address:'Up',
        field:'Front-End Engineer'
    },
    {
        number: 11,
        name: "Shanu",
        ticket:6,
        rating:3,
        exam:2,
        more:'More Details',
        fullname:'Shanu Saini',
        contact:'+91 841848488',
        email:'Shanu@gmail.com',
        address:'Canada',
        field:'Software-Developer'
    },
    {
        number: 12,
        name: "Robin",
        ticket:12,
        rating:5,
        exam:5,
        more:'More Details',
      fullname:'Robin Kamboj',
      contact:'+91 994851452',
      email:'Robin@gmail.com',
      address:'Haryana',
      field:'Agriculture'
    },
    {
        number: 13,
        name: "Ritik",
        ticket:13,
        rating:2,
        exam:1,
        more:'More Details',
      fullname:'Ritik Kamboj',
      contact:'+91 628565582',
      email:'ritik@gmail.com',
      address:'Punjab',
      field:' Management'
    },
    {
        number: 14,
        name: "Shivam",
        ticket:14,
        rating:1,
        exam:4,
        more:'More Details',
      fullname:'Shivam',
      contact:'+91 566488514',
      email:'Shivam@gmail.com',
      address:'Haryana',
      field:'Hotal Management'
    },
    {
        number: 15,
        name: "Harsh",
        ticket:15,
        rating:0,
        exam:0,
        more:'More Details',
      fullname:'Harsh Singh',
      contact:'+91 6000000000',
      email:'Harsh@gmail.com',
      address:'UK',
      field:'MBA'
    },
    {
      number: 16,
      name: "Rohit",
      ticket:16,
      rating:2,
      exam:3,
      more:'More Details',
      fullname:'Rohit Matta',
      contact:'+91 755777447',
      email:'RohitMatta@gmail.com',
      address:'Haryana',
      field:'MBA'
  },
  {
    number: 17,
    name: "Sanam",
    ticket:17,
    rating:2,
    exam:6,
    more:'More Details',
    fullname:'Sanam Kamboj',
    contact:'+91 755667447',
    email:'Sanam@gmail.com',
    address:'Karnal',
    field:'Cse'
},
{
  number: 18,
  name: "Sonam",
  ticket:18,
  rating:1,
  exam:1,
  more:'More Details',
  fullname:'Sonam ',
  contact:'+91 755667447',
  email:'Sonam@gmail.com',
  address:'Indri',
  field:'ECE'
},
    
  ];
  students.forEach((student) => {
    const overallGrade = student.rating + student.exam;
    student.overallGrade = overallGrade;
    student.status = overallGrade >= 4.0 ? "pass" : "fail";
  });
  export default students;